#!/bin/bash

echo "GITHUB AWESOME LISTS ARE AWESOME!! (pre-merge)"
echo ""
echo "    /\\_/\\  "
echo "   ( o.o ) "
echo "    > ^ <  "
echo "   /     \\ "
echo "  (  d   b )"
echo "   \\  ~  /"
echo "    \\   /"
echo "     \\_/"
echo "    \\o/"
echo "     |"
echo "    / \\"
echo ""
echo "   *dancing happily*"
